swagger: "2.0"
info:
  description: |
    Official & Core API for ADT

    [ADT](http://adtcore.io)  Main API

  version: "1.0.0"
  title: ADT API
  termsOfService: http://adtcore.io/terms/
  contact:
    name: team@adtcore.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
# host: api.adtcore.io
# basePath: /v1
# schemes:
#   - http
paths:
  /patients:
    get: 
      tags: 
        - patients
      summary: get's a list of patients
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          description: Number of patients to fetch
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: offset
          in: query
          description: non-negative offset integer for fetching patients
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Patients"
        "400":
          description: Invalid status value
      security:
        - adt_auth:
          - read_patients
    post:
      tags:
        - patients
      summary: Add a new patient to the facility
      description: ""
      operationId: addPatient
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Patient object being added to facility
          required: false
          schema:
            $ref: "#/definitions/Patient"
      responses:
        "201":
          description: Patient Added Successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Patient"
        "405":
          description: Invalid input
      security:
        - adt_auth:
          - create_patients
          - read_patients

  /patients/{patientId}:
    get:
      tags:
        - patients
      summary: Find patient by patientId
      description: Returns the patient with the specified patientId
      operationId: getPatientById
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: patientId
          description: ID of patient that needs to be fetched
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: Patient not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Patient"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
        - adt_auth:
          - create_patients
          - read_patients
    put:
      tags:
        - patients
      summary: Update an existing patient
      description: ""
      operationId: updatePatient
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Patient object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/Patient"
        - in: path
          name: patientId
          description: Patient id to delete
          required: true
          type: integer
          format: int64     
      responses:
        "405":
          description: Validation exception
        "404":
          description: Patient not found
        "400":
          description: Invalid ID supplied
      security:
        - adt_auth:
          - create_patients
          - read_patients    
    delete:
      tags:
        - patients
      summary: Deletes a patient
      description: ""
      operationId: deletePatient
      produces:
        - application/json
        - application/xml
      parameters:
        - in: header
          name: api_key
          description: ""
          required: true
          type: string
        - in: path
          name: patientId
          description: Patient id to delete
          required: true
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid patient value
        "204":
          description: Patient deleted
      security:
        - adt_auth:
          - create_patients
          - read_patients
  /lists/illnesses:
    get:
      tags:
        - lists
      summary: Fetch Chronic Illnesses (for select options)
      description:  Fetch Chronic Illnesses (for select options)
      operationId: ChronicIllnesses
      produces:
        - application/json
      parameters:
        - in: query
          name: tags
          description: Tags to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/ChronicIllnesses"
        "400":
          description: Invalid tag value
      security:
        - adt_auth:
          - read_illnesses
  /lists/allergies:
    get:
      tags:
        - lists
        - Allergies
      summary: Fetch Drug Allergies  (for select options)
      description:  Fetch Drug Allergies  (for select options)
      operationId: DrugAllergies
      produces:
        - application/json
      parameters:
        - in: query
          name: tags
          description: Tags to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/PatientDrugAllergy"
        "400":
          description: Invalid tag value
      security:
        - adt_auth:
          - read_allergies
  /lists/patientsources:
    get:
      tags:
        - lists
        - Allergies
      summary: Fetch Drug Allergies  (for select options)
      description:  Fetch Drug Allergies  (for select options)
      operationId: PatientSources
      produces:
        - application/json
      parameters:
        - in: query
          name: tags
          description: Tags to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/PatientSources"
        "400":
          description: Invalid tag value
      security:
        - adt_auth:
          - read_patientsources
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  adt_auth:
    type: oauth2
    authorizationUrl: http://api.adtcore.io/api/oauth/dialog
    flow: implicit
    scopes:
      create_patients: Create patients
      read_patients: Read your patients
      read_illnesses: Read Chronic Illnesses
      read_allergies: Read Drug Allergies
      read_patientsources: Read Patient Sources
definitions:
  Appointment: 
    type: object
    properties:
      id: 
        type: integer
        format: init64
      appointment_date: 
        type: string
        example: 2016-10-02
      is_appointment:
        type: integer
        format: init64
      facility_id: 
        type: integer
        format: init64
  Regimen:
    type: object
    properties:
      id:
        type: integer
        format: int64
      code: 
        type: string
      name: 
        type: string
      is_active:
        type: integer
        format: int64
      service_id:
        type: integer
        format: int64
      category_id:
        type: integer
        format: int64
  PatientPartner:
    type: object
    properties:
      partnerId:
        type: integer
        format: init64
      status:
        type: string
        example: Single
  Drug:
    type: object
    properties:
      id: 
        type: integer
        format: init64
      name: 
        type: string
      pack_size:
        type: integer
        format: init64
      duration:
        type: integer
        format: init64
      quantity:
        type: integer
        format: init64
      is_arv:
        type: boolean
      is_tb:
        type: boolean
      is_active:
        type: boolean
      unit_id:
        type: integer
      dose_id:
        type: integer
      generic_id:
        type: integer
      supporter_id:
        type: integer
        
  PatientDrugAllergy:
    type: object
    properties:
      drug_id:
        type: integer
        format: init64
      drugrallergy:
        type: string
      is_active:
        type: boolean
  
  ChronicIllnesses:
    type: object
    properties:
      illness_id:
        type: integer
        format: init64
      illness:
        type: string
      is_active:
        type: boolean
 
  PatientSources:
    type: object
    properties:
      source_id:
        type: integer
        format: init64
      source:
        type: string
      is_active:
        type: boolean
         
  PatientDrugOther:
    type: object
    properties:
      patient_id:
        type: integer
        format: init64
      allergy_name:
        type: string
      
  FamilyPlanning:
    type: object
    properties:
      id: 
        type: integer
        format: init64
      name: 
        type: string
        example: Vasectomy
    
  PatientFamilyPlanning:
    type: object
    properties: 
      patientId:
        type: integer
        format: init64
      family_planning_id:
        $ref : "#/definitions/FamilyPlanning"
  
  Visit:
    type: object
    properties:
      id:
        type: integer
        format: init64
      current_height:
        type: integer
        format: init64
      current_weight:
        type: integer
        format: init64
      visit_date: 
        type: string
        example: 2016-10-0
      appointment_adherence:
        type: integer
        format: init64
      is_active:
        type: integer
        format: init64
      patient_id:
        type: integer
        format: init64
      facility_id:
        type: integer
        format: init64
      user_id: 
        type: integer
        format: init64
      purpose_id: 
        type: integer
        format: init64
      last_regimen_id:
        type: integer
        format: init64
      current_regimen_id:
        type: integer
        format: init64
      change_reason_id:
        type: integer
        format: init64
      non_adherence_reason_id:
        type: integer
        format: init64
      appointment_id:
        type: integer
        format: init64
      regimen: 
        $ref: "#/definitions/Regimen"
  
  Status:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        
  Patient_status:
    type: object
    properties:
      patient_id: 
        type: integer
        format: int64
      status_id:
        type: integer
        format: int64
      change_date:
        type: string
        example: 2016-10-0
      status:
        $ref : "#/definitions/Status"
        
  Patients:
    type: object
    required:
      - first_name
      - id
    properties:
      id:
        type: integer
        format: int64
      ccc_number:
        type: string
        example: ABC123456
      appointment:
        $ref: "#/definitions/Appointment"
      visit: 
        $ref: "#/definitions/Visit"
      first_name:
        type: string
        example: John
      last_name:
        type: string
        example: John
      other_name:
        type: string
        example: John
      phone_number:
        type: integer
        format: int64
      alternate_number:
        type: integer
        format: int64
      physical_address:
        type: string
        example: Nairobi West
      gender:
        type: string
        example: male,female
      birth_date:
        type: string
        format: date-time
      enrollment_date:
        type: string
        format: date-time
      support_group:
        type: string
        example: lorem ipsum
      is_pregnant:
        type: boolean
      is_tb:
        type: boolean
      is_tb_tested:
        type: boolean
      is_smoke:
        type: boolean
      is_alchohol:
        type: boolean
      is_sms:
        type: boolean
      deleted_at:
        type: string
      patient_status:
        $ref: "#/definitions/Patient_status"

  Patient:
    type: object
    properties:
      id:
        type: integer
        format: int64
      ccc_number:
        type: string
        example: ABC123456
      first_name:
        type: string
        example: John
      last_name:
        type: string
        example: John
      other_name:
        type: string
        example: John
      phone_number:
        type: integer
        format: int64
      alternate_number:
        type: integer
        format: int64
      physical_address:
        type: string
        example: Nairobi West
      gender:
        type: string
        example: male,female
      birth_date:
        type: string
        format: date-time
      enrollment_date:
        type: string
        format: date-time
      support_group:
        type: string
        example: lorem ipsum
      is_pregnant:
        type: boolean
      is_tb:
        type: boolean
      is_tb_tested:
        type: boolean
      is_smoke:
        type: boolean
      is_alchohol:
        type: boolean
      is_sms:
        type: boolean
      deleted_at:
        type: string
      patient_status:
        $ref: "#/definitions/Patient_status"
      appointment:
        $ref: "#/definitions/Appointment"
      visit: 
        $ref: "#/definitions/Visit"
      patient_partner:
        $ref: "#/definitions/PatientPartner"
      patient_family_planning:
        $ref: "#/definitions/PatientFamilyPlanning"
      patient_drug_allergy:
        $ref: "#/definitions/PatientDrugAllergy"
      patient_drug_other:
        $ref: "#/definitions/PatientDrugOther"